// Priority levels for a todo item
export type TodoPriority = 'low' | 'medium' | 'high';

// Filter options for the todo list
export type TodoFilter = 'all' | 'active' | 'completed';

// The core todo domain model
export interface Todo {
  id: string;          // Stable UUID generated by expo-crypto
  title: string;       // Required, 1–200 characters
  description: string; // Optional context; empty string when not set
  completed: boolean;
  priority: TodoPriority;
  createdAt: string;   // ISO 8601 — safe for serialization to any storage
  updatedAt: string;   // ISO 8601 — updated on every mutation
  dueDate: string | null; // ISO 8601 date string (YYYY-MM-DD) or null
}

// Input for creating a todo — id and timestamps are generated internally
export type CreateTodoInput = Omit<Todo, 'id' | 'createdAt' | 'updatedAt'>;

// Input for updating a todo — id and createdAt are immutable
export type UpdateTodoInput = Partial<Omit<Todo, 'id' | 'createdAt'>>;

// Represents the async result from repository operations
export type RepositoryResult<T> =
  | { success: true; data: T }
  | { success: false; error: string };
